# Default configuration for training and running the model

data:
  train_videos: "data_samples/train-videos/"
  val_videos: "data_samples/val-videos/"
  train_motion_fields: "data_samples/train-motion-fields/"
  val_motion_fields: "data_samples/val-motion-fields/"

test:
  source_image: "samples/source.jpg"
  driving_video: "samples/driving.mp4"
  output_video: "results/result.mp4"
  checkpoint: "checkpoints/g_checkpoint.pth"
  image_size: 128
  device: "cuda"

logs: "log/"
logs_losses: "log/losses_log.csv"
checkpoints: "checkpoints/"

training:
  batch_size: 4
  num_epochs: 500
  learning_rate: 0.00001

model:
  generator: "networks/generator.py"
  discriminator: "networks/discriminator.py"



